name: Auto-close External Pull Requests

on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  auto_close:
    uses: appwrite/.github/.github/workflows/autoclose.yml@main
    secrets:
      GH_AUTO_CLOSE_PR_TOKEN: ${{ secrets.GH_AUTO_CLOSE_PR_TOKEN }}
